"use client";

import { useEffect, type MutableRefObject } from "react";

import { captionIndexAt, CAPTIONS } from "@/lib/demo/story";
import { formatClock, formatCount, formatElapsed, verdict, waitBars, waitGap } from "@/lib/demo/format";
import { loadPercent } from "@/lib/demo/load";
import type { VizEngine } from "@/lib/viz/engine";
import { hasWaitColumns, meanWaitAt } from "@/lib/wait";
import type { LiveHandles } from "./Scoreboard";

/** Readout refresh cap (5 Hz) — the numbers move far slower than the frame rate. */
const REFRESH_MS = 200;

/**
 * Drive a scoreboard straight from the render loop.
 *
 * Everything is written to the DOM by hand rather than through React state:
 * the clip plays at 8x, so a re-render five times a second for numbers that
 * barely move would be a waste of the frame budget. This is the same technique
 * WaitHud uses in the research tool.
 *
 * Both comparisons on the page — the single junction and the hundred-junction
 * city — use this, so the words a visitor reads are generated by one piece of
 * code from one statistic.
 */
export function useLiveCompare(
  engine: VizEngine | null,
  active: boolean,
  handles: MutableRefObject<LiveHandles>,
  options: { captions?: boolean } = {},
): void {
  const withCaptions = options.captions ?? false;

  useEffect(() => {
    if (!engine || !active) return;
    let last = 0;
    let captionIndex = -1;
    let shownLeader = "";

    const write = (el: HTMLElement | null, text: string) => {
      if (el && el.textContent !== text) el.textContent = text;
    };

    const sync = () => {
      const now = performance.now();
      if (now - last < REFRESH_MS) return;
      last = now;

      const h = handles.current;
      const clock = engine.clock;
      const views = [engine.getView(0), engine.getView(1)];
      const wait: [number, number] = [NaN, NaN];

      for (let side = 0; side < 2; side++) {
        const view = views[side];
        if (!view) continue;
        if (hasWaitColumns(view.waitCols)) {
          wait[side] = meanWaitAt(
            view.scan.metrics,
            view.scan.m,
            view.waitCols,
            view.frameIndexAt(clock),
          );
        }
        write(h.wait[side], formatClock(wait[side]));
        write(h.cars[side], formatCount(view.metricAt(clock, view.throughputCol)));
      }

      // The bars carry the comparison: whichever light has cost its drivers
      // more waiting fills the track, and the other one is visibly shorter.
      const bars = waitBars(wait[0], wait[1]);
      if (h.bar[0]) h.bar[0].style.width = `${bars.fixed.toFixed(1)}%`;
      if (h.bar[1]) h.bar[1].style.width = `${bars.responsive.toFixed(1)}%`;

      const v = verdict(waitGap(wait[0], wait[1]));
      if (v.leader !== shownLeader) {
        shownLeader = v.leader;
        if (h.verdictBox) h.verdictBox.dataset.lead = v.leader;
        // The winner's badge appears on its row and on its half of the
        // picture, so the answer is in shot wherever the visitor is looking.
        const ahead: [boolean, boolean] = [v.leader === "fixed", v.leader === "responsive"];
        for (let side = 0; side < 2; side++) {
          if (h.pill[side]) h.pill[side]!.hidden = !ahead[side];
          if (h.stageFlag[side]) h.stageFlag[side]!.hidden = !ahead[side];
        }
      }
      write(h.verdictHead, v.headline);
      write(h.verdictDetail, v.detail);

      if (withCaptions) {
        const index = captionIndexAt(clock.time);
        if (index !== captionIndex) {
          captionIndex = index;
          write(h.caption, CAPTIONS[index].text);
        }
      }

      write(h.elapsed, formatElapsed(clock.time, clock.duration));
      if (h.trackFill) {
        h.trackFill.style.width = `${loadPercent(clock.time, clock.duration).toFixed(2)}%`;
      }
    };

    engine.afterFrame.add(sync);
    return () => {
      engine.afterFrame.delete(sync);
    };
  }, [engine, active, handles, withCaptions]);
}
