"use client";

import { useEffect, type MutableRefObject } from "react";

import { captionIndexAt, CAPTIONS } from "@/lib/demo/story";
import { describeGap, formatClock, formatCount, formatElapsed, waitBars, waitGap } from "@/lib/demo/format";
import {
  fasterReadout,
  hasSpeedWindow,
  percentFaster,
  savedReadout,
  savedSeconds,
  speedColumn,
  trailingMean,
  windowFrames,
} from "@/lib/demo/savings";
import { loadPercent } from "@/lib/demo/load";
import type { VizEngine } from "@/lib/viz/engine";
import { hasWaitColumns, meanWaitAt } from "@/lib/wait";
import type { LiveHandles } from "./Scoreboard";

/** Readout refresh cap (5 Hz) — the numbers move far slower than the frame rate. */
const REFRESH_MS = 200;

/**
 * Drive a scoreboard straight from the render loop.
 *
 * Everything is written to the DOM by hand rather than through React state:
 * the clip plays at 8x, so a re-render five times a second for numbers that
 * barely move would be a waste of the frame budget. This is the same technique
 * WaitHud uses in the research tool.
 *
 * The hero it writes is waiting that did not happen — the difference between
 * the two runs' accumulated delay — because the two runs are the same network,
 * the same demand and the same seed, so that difference is precisely what one
 * light spared its drivers and the other did not. See `lib/demo/savings.ts` for
 * why that, rather than either side's running average or its queue length, is
 * the number in the largest type on the page.
 *
 * Both comparisons on the page — the single junction and the hundred-junction
 * city — use this, so the words a visitor reads are generated by one piece of
 * code from one set of statistics.
 */
export function useLiveCompare(
  engine: VizEngine | null,
  active: boolean,
  handles: MutableRefObject<LiveHandles>,
  options: { captions?: boolean } = {},
): void {
  const withCaptions = options.captions ?? false;

  useEffect(() => {
    if (!engine || !active) return;
    let last = 0;
    let captionIndex = -1;
    let shownLeader = "";

    const write = (el: HTMLElement | null, text: string) => {
      if (el && el.textContent !== text) el.textContent = text;
    };

    const sync = () => {
      const now = performance.now();
      if (now - last < REFRESH_MS) return;
      last = now;

      const h = handles.current;
      const clock = engine.clock;
      const views = [engine.getView(0), engine.getView(1)];
      const wait: [number, number] = [NaN, NaN];
      const delay: [number, number] = [NaN, NaN];
      const speed: [number, number] = [NaN, NaN];

      for (let side = 0; side < 2; side++) {
        const view = views[side];
        if (!view) continue;
        const frame = view.frameIndexAt(clock);
        if (hasWaitColumns(view.waitCols)) {
          wait[side] = meanWaitAt(view.scan.metrics, view.scan.m, view.waitCols, frame);
        }
        delay[side] = view.metricAt(clock, view.delayCol);
        // Instantaneous mean speed swings hard frame to frame, so the live
        // percentage is read over a trailing minute of sim time instead — and
        // withheld entirely until enough clip exists for it to be honest.
        speed[side] = hasSpeedWindow(frame, view.scan.dt)
          ? trailingMean(
              view.scan.metrics,
              view.scan.m,
              speedColumn(view.traj.meta.metrics),
              frame,
              windowFrames(view.scan.dt),
            )
          : NaN;
        write(h.wait[side], formatClock(wait[side]));
        write(h.cars[side], formatCount(view.metricAt(clock, view.throughputCol)));
      }

      // The hero: waiting one light spared its drivers that the other did not.
      // Positive means the responsive signal is the one saving time; the words
      // flip if the file ever says otherwise.
      const saved = savedReadout(savedSeconds(delay[0], delay[1]));
      write(h.savedValue, saved.value);
      write(h.savedLine, saved.line);

      const faster = fasterReadout(percentFaster(speed[0], speed[1]));
      write(h.fasterValue, faster.value);
      write(h.fasterLine, faster.line);

      // The bars carry the settling averages: whichever light has cost its
      // drivers more waiting fills the track, and the other is visibly shorter.
      const gap = waitGap(wait[0], wait[1]);
      const bars = waitBars(wait[0], wait[1]);
      if (h.bar[0]) h.bar[0].style.width = `${bars.fixed.toFixed(1)}%`;
      if (h.bar[1]) h.bar[1].style.width = `${bars.responsive.toFixed(1)}%`;
      write(h.gapLine, `${describeGap(gap)}.`);

      // Everything on the page follows the hero, so the badges, the panel
      // colour and the big number can never contradict one another.
      if (saved.leader !== shownLeader) {
        shownLeader = saved.leader;
        if (h.heroBox) h.heroBox.dataset.lead = saved.leader;
        // The winner's badge appears on its row and on its half of the
        // picture, so the answer is in shot wherever the visitor is looking.
        const ahead: [boolean, boolean] = [
          saved.leader === "fixed",
          saved.leader === "responsive",
        ];
        for (let side = 0; side < 2; side++) {
          if (h.pill[side]) h.pill[side]!.hidden = !ahead[side];
          if (h.stageFlag[side]) h.stageFlag[side]!.hidden = !ahead[side];
        }
      }

      if (withCaptions) {
        const index = captionIndexAt(clock.time);
        if (index !== captionIndex) {
          captionIndex = index;
          write(h.caption, CAPTIONS[index].text);
        }
      }

      write(h.elapsed, formatElapsed(clock.time, clock.duration));
      if (h.trackFill) {
        h.trackFill.style.width = `${loadPercent(clock.time, clock.duration).toFixed(2)}%`;
      }
    };

    engine.afterFrame.add(sync);
    return () => {
      engine.afterFrame.delete(sync);
    };
  }, [engine, active, handles, withCaptions]);
}
